### PR TITLE
Fix #29 issue with better browser rules logic

### LINKED ISSUE #29: Disabling for subdomain then domain puts subdomain menu item in incorrect state
1. Disable for subdomain, e.g. `forums.macurmors.com`.
1. Open another tab and disable for the domain of the above step, e.g. `macrumors.com`.
1. Subdomain menu item will show "Enabled for forums.macrumors.com"
screen shot 2017-12-05 at 3 03 17 pm
@choco

### PR DESCRIPTION
**Pull request by choco**
I was actually suuuuper lazy with previous implementation, should work properly now. Also simplified other parts of my code.

Oh and since I changed the structure of `BrowserRule`, previous browser rules won't work, but since there hasn't been a public release still it shouldn't be a problem!

### CODE REVIEW

**Comment by thompsonate** [comment]
Does disabling for a domain remove all the existing subdomain rules? I think it would be nice if it wasn't destructive, so it would still respect original subdomain disable rules when the domain rule is toggled.

**Comment by choco** [comment]
Yes it removes all subdomain rules. This is because we’d have to deal with two possible rules for a subdomain, one which should enable night shift as an exception and one which should disable it. I could keep the rules but it would add another layer of complexity and I really want to refactor some of the state code before doing that.

**Comment by thompsonate** [comment]
Those two possible rules for subdomains already exist. You can disable for s subdomain or if the domain is disabled, you can enable the subdomain. I understand that it would be a little more complex, but would it hurt anything to have the disable for domain and disable for subdomain rules coexist? Or is it structured differently than I'm thinking?

Go ahead with the refactor though. A lot has changed since I wrote some of that code, so it probably needs it more than I think it does.

**Comment by choco** [comment]
Yes, you're right. I pushed a PR with the change. The refactor is taking quite sometime, and since it's also quite opinionated at least I can push this feature without depending on that.

**Pull request merged**
