### PR TITLE
Clean up code, fix #7

### LINKED ISSUE #7: Feature request: macOS dark mode
It would be great if macOS's dark mode could automatically be enabled with Night Shift. That's pretty much the only feature of F.lux that I miss. Good job with this, it's really helpful! 👍🏽

### PR DESCRIPTION
**Pull request by saagarjha**
This pull request:

1. Adds a .gitignore so that every little change doesn't get staged accidentally
2. Cleans up some code to make it more clear or less verbose
3. Fixes #7. Note: this uses private API from SkyLight.framework (specifically, `SLSSetAppearanceThemeLegacy`).

### CODE REVIEW

**Comment by calda** [comment]
👏🏻 +1

**Comment by thompsonate** [comment]
Looks great and really thorough! Thanks for doing this so now I don't have to figure it out.

**Comment by saagarjha** [comment]
@thompsonate I've been thinking about my solution, and was wondering if it would work if my computer was asleep. Is a `nightShiftToggled` notification posted on wake?

**Comment by thompsonate** [comment]
I think it usually is, but sometimes there are issues with it not being in the correct state on wake. Maybe Shifty is interfering with it somehow. I'm working on a solution that will have Shifty check and make sure it matches the schedule. I think this will be better for Dark Mode too, since it can match the schedule instead of being disabled along with Night Shift when the user disables it temporarily through Shifty.

**Pull request merged**
